# Copyright (c) 2021 2bllw8
# SPDX-License-Identifier: GPL-3.0-only
android_library(
    name = "shell",
    manifest = "AndroidManifest.xml",
    resource_files = glob([
        "res/**",
    ]),
    visibility = [
        "//java/eu/bbllw8/anemo/documents:__pkg__",
        "//java/eu/bbllw8/anemo/editor:__pkg__",
        "//java/eu/bbllw8/anemo/password:__pkg__",
        "//java/eu/bbllw8/anemo/receiver:__pkg__",
        "//java/eu/bbllw8/anemo/snippet:__pkg__",
    ],
    deps = [
    ],
)
