# Copyright (c) 2021 2bllw8
# SPDX-License-Identifier: GPL-3.0-only
load("@rules_android//android:rules.bzl", "android_library")

android_library(
    name = "shell",
    manifest = "AndroidManifest.xml",
    resource_files = glob([
        "res/**",
    ]),
    visibility = [
        "//java/eu/bbllw8/anemo/documents:__pkg__",
    ],
    deps = [
    ],
)
