# Copyright (c) 2021 2bllw8
# SPDX-License-Identifier: GPL-3.0-only
android_library(
    name = "shell",
    manifest = "AndroidManifest.xml",
    resource_files = glob([
        "res/**",
    ]),
    visibility = [
        "//java/eu/bbllw8/anemo/editor/main:__pkg__",
        "//java/eu/bbllw8/anemo/documents/password:__pkg__",
        "//java/eu/bbllw8/anemo/documents/provider:__pkg__",
        "//java/eu/bbllw8/anemo/documents/receiver:__pkg__",
        "//java/eu/bbllw8/anemo/documents/snippet:__pkg__",
    ],
    deps = [
    ],
)
