---
name: Feature request
description: Suggest a feature to add
labels: [enhancement]
title: "[Feature request] "
body:
  - type: textarea
    attributes:
      label: Describe what you'd like to see added to the app
      placeholder: Describe what feature you are requesting and what problems it would solve
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      placeholder: Add any other information or screenshots about the feature request here
    validations:
      required: false
