# Copyright (c) 2021 2bllw8
# SPDX-License-Identifier: GPL-3.0-only
android_library(
    name = "config",
    srcs = glob([
        "**/*.java",
    ]),
    manifest = "AndroidManifest.xml",
    visibility = [
        "//java/eu/bbllw8/anemo/editor/main:__pkg__",
    ],
    deps = [
        "@maven//:androidx_annotation_annotation",
    ],
)
