name: Anemo CI

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'Android.bp'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'Android.bp'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Project checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Load cache
        uses: actions/cache@v2
        with:
          path: '/home/runner/.cache/bazel'
          key: bazel
      - name: Install bazelisk
        run: |
          curl -LO 'https://github.com/bazelbuild/bazelisk/releases/download/v1.7.5/bazelisk-linux-amd64'
          mkdir -p '${GITHUB_WORKSPACE}/bin/'
          mv bazelisk-linux-amd64 '${GITHUB_WORKSPACE}/bin/bazel'
          chmod +x '${GITHUB_WORKSPACE}/bin/bazel'
      - name: Build
        run: |
          '${GITHUB_WORKSPACE}/bin/bazel' build //...
      - name: Upload artifacts
        if: ${{ github.event_name == 'push' }}
        uses: actions/upload-artifact@v2
        with:
          name: app.apk
          path: bazel-bin*/app.apk
          retention-days: 14
